# Generated by Django 4.0.5 on 2022-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_reg',
            name='username',
        ),
        migrations.AddField(
            model_name='seller_reg',
            name='name',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
