# Generated by Django 4.0.5 on 2022-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0002_remove_seller_reg_username_seller_reg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_reg',
            name='name',
        ),
        migrations.AddField(
            model_name='seller_reg',
            name='username',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
