# Generated by Django 4.0.5 on 2022-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0003_remove_seller_reg_name_seller_reg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_reg',
            name='username',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
