# Generated by Django 4.0.5 on 2022-11-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0004_alter_seller_reg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('available_quntity', models.BigIntegerField()),
                ('product_discription', models.CharField(max_length=600)),
                ('percentege_discount', models.BigIntegerField()),
                ('MRP', models.BigIntegerField()),
                ('discount_price', models.BigIntegerField()),
                ('image', models.CharField(max_length=200)),
                ('Seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rephone_seller.seller_reg')),
            ],
        ),
    ]
