# Generated by Django 4.0.5 on 2022-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0005_seller_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_add_product',
            name='available_quntity',
            field=models.SmallIntegerField(),
        ),
    ]
