# Generated by Django 4.0.5 on 2022-11-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0006_alter_seller_add_product_available_quntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_add_product',
            old_name='available_quntity',
            new_name='Available_quntity',
        ),
    ]
