# Generated by Django 4.0.5 on 2022-11-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0007_rename_available_quntity_seller_add_product_available_quntity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_add_product',
            name='Available_quntity',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
