# Generated by Django 4.0.5 on 2022-11-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0009_rename_available_quntity_seller_add_product_available_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_add_product',
            old_name='product_discription',
            new_name='product_description',
        ),
    ]
