# Generated by Django 4.0.5 on 2022-11-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0010_rename_product_discription_seller_add_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_add_product',
            old_name='percentege_discount',
            new_name='percentage_discount',
        ),
    ]
