# Generated by Django 4.0.5 on 2022-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephone_seller', '0011_rename_percentege_discount_seller_add_product_percentage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_add_product',
            name='discount_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller_add_product',
            name='percentage_discount',
            field=models.CharField(max_length=20),
        ),
    ]
